version: "3.9"
services:
  server:
    build: ./server

    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"

  client:
    build: 
      context: ./server
      args:
        VITE_API_URL: http://3.26.242.54:5000/api

    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - FLASK_API_URL=http://server:5000
    depends_on:
      - server