version: "3.9"
services:
  flask_api:
    build: ./flask_api
    ports:
      - "5000:5000"

  node_server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - FLASK_API_URL=http://flask_api:5000
    depends_on:
      - flask_api